### ISSUE TITLE
Setting password process

### ISSUE THREAD

**Issue by aginies** [AllanOricil/esp32-mfa-authenticator#24]
The password configuration is a bit strange.
You are asking for an hash and a key but not for a pin?
So its up to us to generate the HMac-SHA256 based on a pin and a key?

Something like this with PIN=4444 and KEY=MYKEY:
echo -n "4444" | openssl dgst -sha256 -hmac "MYKEY" | awk '{print $2}'

And populate with the result the hash and the key?
I have tried but this  was not working at all.
Could you point me out whats my problem?

regards.

**Comment by AllanOricil** [comment]
@aginies thank you for asking that. I could swear I had a doc section talking about it in more details. I will add it again.

This is how you can hash you pin number

1. Open this https://www.devglan.com/online-tools/hmac-sha256-online
2. Add you pin number as plain, and use numbers only because the UI doesnt support anything else yet.
3. Use this other website to create a strong secret to hash your pin number
4. Take notes of the generated hash

<img width="1387" alt="image" src="https://github.com/user-attachments/assets/71da964f-7005-4098-9443-d7ee0cacbf06">

5. In your config.yml

```yml
...
security: 
  pin: 
    hash: 5f3c7b414e0d69e5394ef40ef3d1163bed0e65af9bf751ff55bc88ab89c1abff
    key: 2TPm3VsZIIwf4vAx2TPm3VsZIIwf4vAx
  max_number_of_wrong_unlock_attempts: 3
...
```

Don't forget to remove the SD card after it has completely booted.
